// GENERATED by scripts/sync-abi.mjs from contracts/out/PolicyVault.sol/PolicyVault.json.
// Do not edit by hand — run `pnpm sync:abi` after changing PolicyVault.sol.
// `pnpm sync:abi --check` fails CI when this file and the compiled contract disagree.

export const policyVaultAbi = [
  {
    "type": "function",
    "name": "AUTHORIZATION_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "allowlisted",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "payee",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "authorization",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "payer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "payTo",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "nonce",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closeGoal",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "decisionHandle",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "ebool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "finalizeDecision",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "approved",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "signatures",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "goalCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "goals",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "payer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "relay",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "callsRemaining",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "open",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isApproved",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isFinalized",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openGoal",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct PolicyVault.OpenGoalParams",
        "components": [
          {
            "name": "budgetCiphertext",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "perCallCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "callsRemaining",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "relay",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "allowlist",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "payerGoal",
    "inputs": [
      {
        "name": "payer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingSeq",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "perCallCap",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "remainingBudgetHandle",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "euint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requestSpend",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "payTo",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "resource",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "spendNonce",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "termsHash",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "validityWindow",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "validAfter",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "validBefore",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "GoalClosed",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GoalOpened",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "relay",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "perCallCap",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "callsRemaining",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "budgetHandle",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SpendFinalized",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "approved",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "decisionHandle",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SpendRequested",
    "inputs": [
      {
        "name": "goalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "seq",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "payTo",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "termsHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "decisionHandle",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "validAfter",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "validBefore",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyFinalized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallFailedAfterFeeRefresh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyAllowlist",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeNotPaid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GoalExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GoalNotOpen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAttestation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidCallCount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidCap",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExpiry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPayer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRelay",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotGoalOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotRelay",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PayeeNotAllowlisted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PayerAlreadyBound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SpendPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownGoal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownSpend",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const;
