[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = []
solc = "0.8.29"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532 }
