#!/usr/bin/env node
// Regenerates the checked-in ABIs from the Foundry artifacts.
//
// The services need each contract's ABI, and Foundry's `out/` is a build product that
// is not checked in — so the ABI has to live in source. Generating it rather than
// hand-maintaining it is what keeps a contract change from silently leaving the
// signer reading a function signature that no longer exists.
//
//   node scripts/sync-abi.mjs            # write
//   node scripts/sync-abi.mjs --check    # fail if out of date (CI)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const repoRoot = new URL("..", import.meta.url).pathname.replace(/^\/([a-zA-Z]:)/, "$1");
const check = process.argv.includes("--check");

/** Each contract whose ABI the TypeScript side consumes. */
const CONTRACTS = [
  { contract: "PolicyVault", file: "policyVault.abi.ts", exportName: "policyVaultAbi" },
  { contract: "TraceAnchor", file: "traceAnchor.abi.ts", exportName: "traceAnchorAbi" },
];

let wrote = 0;
let skipped = 0;

for (const { contract, file, exportName } of CONTRACTS) {
  const artifactPath = join(repoRoot, "contracts", "out", `${contract}.sol`, `${contract}.json`);
  const outPath = join(repoRoot, "packages", "shared", "src", "chain", file);

  if (!existsSync(artifactPath)) {
    // In the TS-only CI job there is no Foundry, so there is no artifact to compare
    // against. Skipping is correct: the contracts job runs `forge build` and this
    // check there.
    skipped++;
    continue;
  }

  const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));

  const banner = `// GENERATED by scripts/sync-abi.mjs from contracts/out/${contract}.sol/${contract}.json.
// Do not edit by hand — run \`pnpm sync:abi\` after changing ${contract}.sol.
// \`pnpm sync:abi --check\` fails CI when this file and the compiled contract disagree.

`;
  const next = banner + `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;

  if (check) {
    const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
    if (current.replace(/\r\n/g, "\n") !== next) {
      console.error(
        `sync-abi: packages/shared/src/chain/${file} is out of date.\n` +
          "Run `pnpm sync:abi` and commit the result.",
      );
      process.exit(1);
    }
    continue;
  }

  writeFileSync(outPath, next);
  console.log(`sync-abi: wrote ${abi.length} ABI entries to packages/shared/src/chain/${file}`);
  wrote++;
}

if (skipped === CONTRACTS.length) {
  console.log("sync-abi: no Foundry artifacts; skipping (run `forge build` in contracts/ first).");
  process.exit(0);
}

if (check) {
  console.log(`sync-abi: ${CONTRACTS.length - skipped} ABI(s) in sync with the compiled contracts.`);
} else if (wrote === 0) {
  console.log("sync-abi: nothing to write.");
}
