#!/usr/bin/env node
// Regenerates packages/shared/src/chain/policyVault.abi.ts from the Foundry artifact.
//
// The services need the vault's ABI, and Foundry's `out/` is a build product that
// is not checked in — so the ABI has to live in source. Generating it rather than
// hand-maintaining it is what keeps a contract change from silently leaving the
// signer reading a function signature that no longer exists.
//
//   node scripts/sync-abi.mjs            # write
//   node scripts/sync-abi.mjs --check    # fail if out of date (CI)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const repoRoot = new URL("..", import.meta.url).pathname.replace(/^\/([a-zA-Z]:)/, "$1");
const artifactPath = join(repoRoot, "contracts", "out", "PolicyVault.sol", "PolicyVault.json");
const outPath = join(repoRoot, "packages", "shared", "src", "chain", "policyVault.abi.ts");

const check = process.argv.includes("--check");

if (!existsSync(artifactPath)) {
  // In the TS-only CI job there is no Foundry, so there is no artifact to compare
  // against. Skipping is correct: the contracts job runs `forge build` and this
  // check there.
  console.log("sync-abi: no Foundry artifact; skipping (run `forge build` in contracts/ first).");
  process.exit(0);
}

const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));

const banner = `// GENERATED by scripts/sync-abi.mjs from contracts/out/PolicyVault.sol/PolicyVault.json.
// Do not edit by hand — run \`pnpm sync:abi\` after changing PolicyVault.sol.
// \`pnpm sync:abi --check\` fails CI when this file and the compiled contract disagree.

`;

const body = `export const policyVaultAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;
const next = banner + body;

if (check) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== next) {
    console.error(
      "sync-abi: packages/shared/src/chain/policyVault.abi.ts is out of date.\n" +
        "Run `pnpm sync:abi` and commit the result.",
    );
    process.exit(1);
  }
  console.log("sync-abi: ABI is in sync with the compiled contract.");
  process.exit(0);
}

writeFileSync(outPath, next);
console.log(`sync-abi: wrote ${abi.length} ABI entries to packages/shared/src/chain/policyVault.abi.ts`);
